---
title: "Uso comun de Git"
subtitle: "con GitHub y RStudio"
author: "https://bookdown.org/maurolepore/git-comun/"
date: "Mauro Lepore"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Ronda 1: Basico | Bifurcar y clonar

* Crear una bifurcacion
* Crear un clon local
* Hacer un cambio, "commit", y empujar
* Confirmar en GitHub

## Ronda 2: Intermedio | Trabajar en un tiquete y solicitar fusion

* Crear una rama local asociada a un tiquete en "upstream"
* Empujar la rama
* Hacer una solicitud de fusion

## Ronda 3: Avanzado | Actualizar la base de la solicitud de fusion

* Hacer un cambio conflictivo desde GitHub en "upstream"
* Confirmar que la solicitud de fusion esta en conflicto
* Actualizar la base de la solicitud de fusion
* Crear una copia de seguridad de la rama
* Forzar empuje
* Confirmar que todo esta bien
* Borrar rama de seguridad local y remota

# Extras (si hay tiempo)

## Configuracion

* Confirmar remoto "origin"
* Confirmar opciones globales
* Editor
* Facilitar "push"
* Evitar conflictos

## Cambiar la historia

* reset
* revert
* rebase